version: "2.4"
services:

#  consul-1:
#    image: consul:1.5
#    hostname: consul-1
#    container_name: consul-1
#    command: consul agent -dev -bind=0.0.0.0 -client=0.0.0.0 -ui
#    ports:
#      - 8500:8500
#    healthcheck:
#      test: [CMD, curl, -f, 'http://localhost:8500/v1/status/leader']
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
#  consul-2:
#    image: consul:1.5
#    hostname: consul-2
#    container_name: consul-2
#    command: consul agent -dev -bind=0.0.0.0 -client=0.0.0.0 -join=consul-1 -ui
#    ports:
#      - 8501:8500
#    depends_on:
#      consul-1:
#        condition: service_healthy
#    links:
#      - consul-1
#    healthcheck:
#      test: [CMD, curl, -f, 'http://localhost:8500/v1/status/leader']
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
#  consul-3:
#    image: consul:1.5
#    hostname: consul-3
#    container_name: consul-3
#    command: consul agent -dev -bind=0.0.0.0 -client=0.0.0.0 -join=consul-1 -ui
#    ports:
#      - 8502:8500
#    depends_on:
#      consul-1:
#        condition: service_healthy
#    links:
#      - consul-1
#    healthcheck:
#      test: [CMD, curl, -f, 'http://localhost:8500/v1/status/leader']
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
#  vault-1:
#    image: vault:1.1.2
#    hostname: vault-1
#    container_name: vault-1
#    command: vault server -config /config/vault.json
#    ports:
#      - 8200:8200
#    depends_on:
#      consul-1:
#        condition: service_healthy
#    links:
#      - consul-1:consul
#    volumes:
#      - ./vault.json:/config/vault.json
#    cap_add:
#      - IPC_LOCK
#
#  vault-2:
#    image: vault:1.1.2
#    hostname: vault-2
#    container_name: vault-2
#    command: vault server -config /config/vault.json
#    ports:
#      - 8201:8200
#    depends_on:
#      consul-2:
#        condition: service_healthy
#    links:
#      - consul-2:consul
#    volumes:
#      - ./vault.json:/config/vault.json
#    cap_add:
#      - IPC_LOCK
#
#  vault-3:
#    image: vault:1.1.2
#    hostname: vault-3
#    container_name: vault-3
#    command: vault server -config /config/vault.json
#    ports:
#      - 8202:8200
#    depends_on:
#      consul-3:
#        condition: service_healthy
#    links:
#      - consul-3:consul
#    volumes:
#      - ./vault.json:/config/vault.json
#    cap_add:
#      - IPC_LOCK

  postgres:
    image: postgres:9.6
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=devtools
      - POSTGRES_USER=devtools
      - POSTGRES_PASSWORD=devtools
    ports:
      - 5432:5432

  redis:
    image: redis:3.2
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
