version: "2"
services:

  ######################################################################################################################
  # Consul (Hashicorp)
  ######################################################################################################################

  consul-1:
    image: consul:1.5
    hostname: consul-1
    container_name: consul-1
    command: consul agent -dev -bind=0.0.0.0 -client=0.0.0.0 -ui
    ports:
      - 8500:8500

  consul-2:
    image: consul:1.5
    hostname: consul-2
    container_name: consul-2
    command: sh -c "sleep 2 && consul agent -dev -bind=0.0.0.0 -client=0.0.0.0 -join=consul-1"
    ports:
      - 8501:8500
    depends_on:
      - consul-1
    links:
      - consul-1

  consul-3:
    image: consul:1.5
    hostname: consul-3
    container_name: consul-3
    command: sh -c "sleep 2 && consul agent -dev -bind=0.0.0.0 -client=0.0.0.0 -join=consul-1"
    ports:
      - 8502:8500
    depends_on:
      - consul-1
    links:
      - consul-1

  ######################################################################################################################
  # Vault (Hashicorp)
  ######################################################################################################################

  vault-1:
    image: vault:1.1.2
    hostname: vault-1
    container_name: vault-1
    volumes:
      - ./vault/vault.json:/config/vault.json
    command: sh -c "sleep 4 && vault server -config /config/vault.json"
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    depends_on:
      - consul-1
    links:
      - consul-1:consul

  vault-2:
    image: vault:1.1.2
    hostname: vault-2
    container_name: vault-2
    volumes:
      - ./vault/vault.json:/config/vault.json
    command: sh -c "sleep 4 && vault server -config /config/vault.json"
    cap_add:
      - IPC_LOCK
    ports:
      - 8201:8200
    depends_on:
      - consul-2
    links:
      - consul-2:consul

  vault-3:
    image: vault:1.1.2
    hostname: vault-3
    container_name: vault-3
    volumes:
      - ./vault/vault.json:/config/vault.json
    command: sh -c "sleep 4 && vault server -config /config/vault.json"
    cap_add:
      - IPC_LOCK
    ports:
      - 8202:8200
    depends_on:
      - consul-3
    links:
      - consul-3:consul

  ######################################################################################################################
  # Traefik (Containous)
  ######################################################################################################################
  traefik:
    image: traefik:1.7-alpine
    hostname: traefik
    container_name: traefik
    command: --configfile=/config/traefik.toml
    volumes:
      - ./traefik/traefik.toml:/config/traefik.toml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on:
      - consul-1
    links:
      - consul-1:consul

  ######################################################################################################################
  # Web (GoMicro)
  ######################################################################################################################
  web:
    image: microhq/micro
    hostname: web
    container_name: web
    command: --enable_stats --registry=consul --registry_address="consul-1:8500,consul-2:8500,consul-3:8500" --server_name="com.pingflow.web" web --namespace="com.pingflow"
    ports:
      - 8001:8082
    depends_on:
      - consul-1
      - consul-2
      - consul-3
    links:
      - consul-1
      - consul-2
      - consul-3

  ######################################################################################################################
  # Api (GoMicro)
  ######################################################################################################################
  api:
    image: microhq/micro
    hostname: api
    container_name: api
    command: --enable_stats --registry=consul --registry_address="consul-1:8500,consul-2:8500,consul-3:8500" --server_name="com.pingflow.api" api --handler=web --namespace="com.pingflow"
    ports:
      - 8000:8080
    depends_on:
      - consul-1
      - consul-2
      - consul-3
    links:
      - consul-1
      - consul-2
      - consul-3
